"use client";
import {useEffect,useState} from "react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
type Candidate={kind:string;text:string;source:string;date:string};
export default function MaterialReview({id,courseId,onClose,onMutate}:{id:string;courseId:string;onClose:()=>void;onMutate:(a:string,p:Record<string,unknown>)=>Promise<void>}) {
 const [items,setItems]=useState<Candidate[]|null>(null),[error,setError]=useState(""),[saved,setSaved]=useState<number[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch(`/api/materials/${encodeURIComponent(id)}/analyze`).then(async r=>{const d=await r.json() as {error?:string;candidates:Candidate[]};if(!r.ok)throw new Error(d.error);setItems(d.candidates);}).catch(e=>setError(e.message));},[id]);
 return <Dialog open onOpenChange={onClose}><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Review syllabus dates and rules</DialogTitle><DialogDescription>Extracted text candidates may be incomplete. Verify the source and confirm each date before adding it. Use Grade lab to enter confirmed category weights.</DialogDescription></DialogHeader>{error&&<p role="alert">{error}</p>}{!items&&!error&&<p>Reading material…</p>}{items?.length===0&&<p>No recognizable dates or rules found. Check the original document.</p>}{items?.map((c,i)=><article key={i} className="review-candidate"><strong>{c.kind} · {c.source}</strong><p>{c.text}</p>{c.kind==="date"&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await onMutate("event:create",{courseId,title:f.get("title"),dueAt:new Date(String(f.get("date"))).toISOString(),description:`Confirmed from ${c.source}\n${c.text}`,kind:"event",estimatedMinutes:60});setSaved(x=>[...x,i]);toast.success("Confirmed date added.");}catch(e){toast.error(e instanceof Error?e.message:"Could not add date.");}finally{setBusy(false);}}}><label>Date title<input name="title" required maxLength={180} defaultValue={c.text.slice(0,180)}/></label><label>Confirm date and time<input name="date" type="datetime-local" required defaultValue={c.date?`${c.date}T23:59`:""}/></label><Button disabled={busy||saved.includes(i)}>{saved.includes(i)?"Added":"Confirm and add date"}</Button></form>}</article>)}</DialogContent></Dialog>;
}
