"use client";
import {useState} from "react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import type {Workspace} from "@/lib/client-types";
export default function ReviewView({data,onMutate}:{data:Workspace;onMutate:(a:string,p:Record<string,unknown>)=>Promise<void>}) {
 const [course,setCourse]=useState(""),[revealed,setRevealed]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const cards=data.cards.filter(c=>!course||c.course_id===course),due=cards.filter(c=>Date.parse(c.due_at)<=Date.now()),card=due[0];
 const review=async(rating:string)=>{if(!card)return;setBusy(true);try{await onMutate("card:review",{id:card.id,rating});setRevealed(null);}catch(e){toast.error(e instanceof Error?e.message:"Could not save review.");}finally{setBusy(false);}};
 return <div className="plan-layout"><section className="content-panel"><p className="eyebrow">SPACED REPETITION</p><h2>Review what needs practice</h2><label>Course<select value={course} onChange={e=>{setCourse(e.target.value);setRevealed(null);}}><option value="">All courses</option>{data.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>{due.length} cards due · {cards.length} saved. Again schedules 10 minutes; hard schedules tomorrow; remembered doubles the interval.</p>{card?<div className="flashcard"><h3>{card.question}</h3>{revealed===card.id?<><p>{card.answer}</p><small>{card.source || "Student-created card"}</small><div className="heading-actions"><Button disabled={busy} variant="outline" onClick={()=>review("again")}>Again</Button><Button disabled={busy} variant="outline" onClick={()=>review("hard")}>Hard</Button><Button disabled={busy} onClick={()=>review("good")}>Remembered</Button></div></>:<Button onClick={()=>setRevealed(card.id)}>Show answer</Button>}</div>:<p>No cards due. Generate cards from selected materials in AI study chat or add your own.</p>}<h3>Topics needing review</h3>{cards.filter(c=>c.reviews>0&&c.interval_days<=1).map(c=><p key={c.id}>{c.question}</p>)}{cards.length>0&&<details><summary>Manage saved cards</summary>{cards.map(c=><div className="assignment-row" key={c.id}><span>{c.question}<small>Next: {new Date(c.due_at).toLocaleString()}</small></span><Button variant="ghost" onClick={()=>onMutate("card:delete",{id:c.id}).catch(e=>toast.error(e.message))}>Delete</Button></div>)}</details>}</section><aside className="content-panel"><h3>Add a flashcard</h3><form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);try{await onMutate("card:create",{courseId:course,question:f.get("question"),answer:f.get("answer"),source:f.get("source")});form.reset();toast.success("Card saved.");}catch(e){toast.error(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}}><label>Question<textarea name="question" required maxLength={1000}/></label><label>Answer<textarea name="answer" required maxLength={3000}/></label><label>Source or topic<input name="source" maxLength={300}/></label><Button disabled={busy}>Save card</Button></form></aside></div>;
}
