import { setting } from "@/lib/server";
import Link from "next/link";

export const metadata = { title: "Privacy notice | Coursewise" };

export default function PrivacyPolicy() {
  const email = setting("COURSEWISE_SUPPORT_EMAIL");
  const operator = setting("COURSEWISE_OPERATOR_NAME");
  return <main className="legal-page">
    <Link href="/">← Coursewise</Link>
    <h1>Coursewise privacy notice</h1>
    <p>Effective October 7, 2026. This notice covers the Coursewise website and Canvas browser extension. {operator ? <>Coursewise is operated by {operator}. </> : <>The legal operator has not been configured for this private preview. </>}Coursewise is intended for students age 13 or older. If you are under 13, do not use it or submit information.</p>
    <h2>Information Coursewise uses</h2>
    <p>For a signed-in workspace, Coursewise stores the account identifier supplied by ChatGPT sign-in; courses, assignments, dates and grade history you enter or connect; study plans and focus sessions; uploaded files, extracted text, indexed passages, and course facts; saved questions, AI replies, conversation summaries, review cards, preferences, and search embeddings derived from selected material excerpts. The sign-in platform may also provide your email and name to the pairing page; Coursewise does not save those fields in its student database. If you connect Canvas through a school-approved OAuth connection, Coursewise reads course, assignment, and calendar data and stores encrypted access credentials needed to keep that connection. A calendar feed URL is used for one import and is not saved.</p>
    <p>After you accept the extension disclosure, the extension reads Canvas courses, grades, assignments, announcements, and visible page text in your signed-in browser to show its organizer. Canvas summaries and page text stay in browser memory unless you choose an action that sends them to Coursewise. The extension stores appearance choices and IDs of items you mark as read in Chrome local storage. Its short-lived pairing token is kept in Chrome session storage and is cleared when the browser session ends.</p>
    <h2>AI study features</h2>
    <p>AI features require a separate opt-in in Data &amp; privacy. When you request study help, Coursewise sends your question and relevant selected material excerpts, course facts, and recent chat context to the OpenAI API. It also sends selected excerpts and questions to OpenAI to create search embeddings. Syllabus analysis can send up to 65,000 characters of a syllabus. An explicit self-harm message caught by Coursewise&apos;s direct safeguard receives a local support response without being sent to OpenAI, though that exchange is saved in your chat. The Responses API requests set <code>store: false</code>. Under <a href="https://platform.openai.com/docs/guides/your-data" target="_blank" rel="noopener noreferrer">OpenAI&apos;s published API data controls</a>, API content is not used to train models by default unless the account opts in, and default abuse-monitoring logs may be kept for up to 30 days. Actual contractual settings must be checked before public launch. Coursewise saves resulting study content and chats in your account. Do not upload or submit material you are not authorized to share.</p>
    <h2>Service providers and security</h2>
    <p>The current preview uses the Sites hosting platform on Cloudflare Workers, D1, and R2 to run the service and store account records and uploads; OpenAI for optional AI and embeddings; and your school&apos;s Canvas service, provided by Instructure, when you connect or use Canvas. The extension connects to the Coursewise site using HTTPS in a production package. Account data is scoped to the signed-in user, and Canvas OAuth tokens are encrypted before storage. This source version has no ad pixels, analytics service, payment processor, or subscription trial. Hosting and provider operational logs or backups may persist under their own retention practices.</p>
    <h2>Your choices and retention</h2>
    <p>In Data &amp; privacy, you can turn AI excerpt sharing off, export workspace data, download original uploads, delete a course, or delete your workspace. We record the date of your 13+ eligibility confirmation. Active workspace records remain until you delete them. Workspace deletion removes account data, original uploads, Canvas credentials, and extension pairing records, while retaining a minimal marker associated with your account identifier to avoid recreating sample data. Deletion cannot recall copies you downloaded or immediately remove provider backups or logs. Browser-local appearance choices and read-item IDs remain until you clear extension storage or remove the extension. Signing out of the extension revokes its current pairing token.</p>
    <p>You can review and correct courses, dates, grades, and study settings in your workspace. For account identity information managed by ChatGPT sign-in, use that provider&apos;s account controls. This version does not collect browsing across other sites for advertising or analytics, so a browser Do Not Track signal does not change its behavior; no third-party ad tracker is embedded in the site.</p>
    <h2>Questions and changes</h2>
    <p>Changes to this notice will appear here with a revised effective date. A new use of student data that requires consent will be presented for a separate choice before it begins. {email ? <>For privacy or accessibility questions or a correction request, contact <a href={`mailto:${email}`}>{email}</a>.</> : <>A public support contact has not been configured for this private preview.</>}</p>
    <p><a href="/accessibility">Accessibility information</a></p>
  </main>;
}
